[package]
name = "ssh-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
dotenv = "0.15.0"
envconfig = "0.11.0"
gethostname = "0.5.0"
log = "0.4.22"
notify = "7.0.0"
pushover = "0.4.0"
regex = "1.11.1"
