services:
  monitor:
    mem_limit: 128m
    image: azurejelly/sshmon:latest
    volumes:
      # Mounts the host's /var/log/ folder inside the container as read-only.
      # We don't need to have write access to it.
      - /var/log:/var/log:ro
    
    # You can use a .env file directly instead of modifying the values below.
    # Just uncomment the following line:
    # env_file: ".env"

    environment:
      # The place where successful SSH logins can normally be found.
      # Ubuntu seems to use /var/log/auth.log and Fedora/CentOS/RHEL
      # seem to use /var/log/secure instead.
      SSH_LOG_PATH: "/var/log/auth.log"

      # The regex that the program will use to identify new successful SSH logins. Optional.
      AUTH_SUCCESS_REGEX: "Accepted (\\w+) for (\\w+) from ([\\d\\.]+) port "
      
      # Valid notifier types are: 'pushover', 'stdout' and 'ntfy'. Required.
      NOTIFIER: "pushover"

      # Pushover API and user keys. Optional unless you're using
      # pushover as the notifier.
      PUSHOVER_API_KEY: "..."
      PUSHOVER_USER_KEY: "..."

      # How this machine should be referred as in each notification.
      # Optional, will use the machine's hostname instead.
      HOSTNAME_OVERRIDE: "sshmon-docker"

      # The log level. Optional. By default this is set to show all logs
      # that have a level equal or higher to 'info'. Set it to 'debug' or
      # 'trace' in order to show debug messages.
      RUST_LOG: "info"
